output_dir: 'exp/output'
log_dir: 'exp/log'
dataset:
  name: 'CASIA-SURF'
  augmentation:
    horizontal_flip: True
    rotation_range: 10
    gamma_correction: [1.0/2.2, 2.2/1.0]
    brightness: 0.5
    contrast: 0.5
    saturation: 0.5
    hue: 0.5
  train_csv: 'tran.csv'
  val_csv: 'val.csv'
  mean: [0.5, 0.5, 0.5]
  sigma: [0.5, 0.5, 0.5]
train:
  from: 'scratch'
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 100
  smoothing: True
val:
  batch_size: 24