output_dir: 'exp/output'
log_dir: 'exp/log'
dataset:
  name: 'CASIA-SURF'
  augmentation:
    horizontal_flip: True
    rotation_range: 10
    gamma_correction: [1.0/2.2, 2.2/1.0]
    brightness: 0.5
    contrast: 0.5
    saturation: 0.5
    hue: 0.5
  train_csv: 'train_list.txt'
  val_csv: 'val.txt'
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
train:
  from: 'scratch'
  rgb_size: [224,224]
  depth_size: [64, 64]
  output_size: 255
  batch_size: 32
  lr: 0.0001
  num_epochs: 100
  smoothing: True
test:
  model: ''
  rgb_size: [224,224]
  depth_size: [64, 64]
  batch_size: 32