output_dir: 'exp/output'
log_dir: 'exp/log'
dataset:
  name: 'CASIA-SURF'
  augmentation:
    horizontal_flip: True
    rotation_range: 10
    gamma_correction: [1.0/2.2, 2.2/1.0]
    brightness: 0.5
    contrast: 0.5
    saturation: 0.5
    hue: 0.5
  train_csv: 'train_list.txt'
  val_csv: 'val_private_list.txt'
  test_csv: 'test_private_list.txt'
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
train:
  from: 'scratch'
  net: 'resnet18-resnet18'
  rgb_size: [128,128]
  depth_size: [64, 64]
  batch_size: 64
  lr: 0.0001
  w_decay: 0.000001
  eps: 0.00000001
  num_epochs: 30
  cmfl_lamb: 0.5
  cmfl_alpha: 1
  cmfl_gamma: 2
test:
  model: '2021-12-18 11_22_46-resnet18-resnet18.pth'
  rgb_size: [224,224]
  batch_size: 32