output_dir: 'exp/output'
log_dir: 'exp/log'
dataset:
  name: 'CASIA-SURF'
  augmentation:
    horizontal_flip: True
    rotation_range: 10
    gamma_correction: [1.0/2.2, 2.2/1.0]
    brightness: 0.5
    contrast: 0.5
    saturation: 0.5
    hue: 0.5
  train_csv: 'train_10_list.txt'
  val_csv: 'val_private_list.txt'
  test_csv: 'test_private_list.txt'
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
train:
  from: 'scratch'
  net: 'resnet18-cdc-simam-fusion'
  rgb_size: [128,128]
  depth_size: [128, 128]
  batch_size: 64
  num_epochs: 100
  optim:
    lr: 0.0001
    wd: 0.000001
    eps: 0.00000001
  cmfl:
    lamb: 0.5
    alpha: 1
    gamma: 3
val:
  batch_size: 64
test:
  model: '2022-04-30 17-02_resnet18-cdc-simam-fusion.pth'
  rgb_size: [128,128]
  batch_size: 64